### ISSUE TITLE
Support fine-grained tokens

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/actions-wiki#2]
[Here are some notes on fine-grained token support](https://github.com/spenserblack/actions-wiki/issues/1#issuecomment-1432144222)

**Comment by jcbhmr** [comment]
I'd like to note that currently

https://github.com/spenserblack/actions-wiki/blob/main/action.yml#L33

you use the `https://TOKEN@github.com/user/repo` format, when it _should_ be `https://USER:TOKEN@github.com/user/repo` for constructing the auth URL so that the TOKEN part is in the _password_ slot of the user:password auth thing. https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#using-a-personal-access-token-on-the-command-line

```
Once you have a token, you can enter it instead of your password when performing Git operations over HTTPS.

For example, on the command line you would enter the following:

$ git clone https://github.com/USERNAME/REPO.git
Username: YOUR_USERNAME
Password: YOUR_TOKEN
```

in this case, I think you can use $GITHUB_ACTOR to use the current trigger-er user as the username. That's what I think is best practice (I vaguely remember seeing that pattern used before) but I can't point to a specific "best practice because $X does it this way" on this. The alternative is GITHUB_REPOSITORY_OWNER which doesn't seem as _semantically correct_ but idk.

**Comment by jcbhmr** [comment]
ref https://github.com/spenserblack/actions-wiki/issues/22 with related discussion about dummy user `https://x:$TOKEN@github.com/user/repo.git` working

**Comment by jcbhmr** [comment]
heres my (admittedly imcomplete) writeup of the github token madness: https://github.com/Andrew-Chen-Wang/github-wiki-action/blob/jcbhmr/wiki/Home.md

**Comment by spenserblack** [comment]
Looks like the link is invalid. Could you find a permalink?

**Comment by jcbhmr** [comment]
Yep! I merged the `jcbhmr` branch stuff into the main branch and deleted it. Oopsies for spreading bad links. https://github.com/Andrew-Chen-Wang/github-wiki-action/wiki
