### ISSUE TITLE
Add more informative error message when wiki doesn't exist

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#27]
![image](https://user-images.githubusercontent.com/61068799/225787346-a9a3680a-fcfa-4c7f-b38f-0c1aba63d679.png)

I was scratching my head for a few minutes before I remembered that I needed to create a dummy wiki page to init it. 🙄 If I forgot that, others will too. Having a nice error message is undoubtedly a good idea 🎉

**Comment by spenserblack** [comment]
Just double-checked since I thought it was pretty weird that the repository doesn't even exist until the initial page is created.

https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages#cloning-wikis-to-your-computer
>Once you've created an initial page on GitHub, you can clone the repository

Apparently there aren't any API endpoints, either, from my quick search.

We can at least use a [GraphQL query](https://docs.github.com/en/graphql/reference/interfaces#repositoryinfo) to detect if the wiki is enabled (it can probably be gotten from the REST API, too).

I was hoping to be able to automatically create the initial page 😞

**Comment by jcbhmr** [comment]
I don't even think you need to do that! You can just `git clone | grep -i 'repository not found'` and if it matches, you know that the repo wasn't found, therefore, show BETTER error message.

**Comment by spenserblack** [comment]
I was thinking about granularly saying what was the issue, but, yeah, one single catchall error message like "please enable the repo and make an initial page" would probably be good enough.

Nitpick: we might try [checking if the repo exists in a separate step](https://stackoverflow.com/a/12170675).

This is because I just generally prefer a `doThing if valid else fail` pattern to `try doThing catch fail`. Though I'll admit this is more nitpicky, and not that related to performance, when bash scripting.

**Comment by jcbhmr** [comment]
Doesn't really matter 🤷‍♂️

I notice a lot of code things are piling up, so I guess it's time to actually do #23 and get on it 👨‍💻👨‍💻

**Comment by spenserblack** [comment]
I think this is overdue:

@all-contributors add @jcbhmr for ideas
