### ISSUE TITLE
How does this compare to newrelic/wiki-sync-action?

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#4]
Context: I have been "shopping" for a wiki sync action to use in my repos.

Adding a comparison section to the readme might be something to consider. I just know I was curious about the differences between this repo and other wiki sync actions that exist. This one is pretty up-to-date in comparison to all the others! Most haven't been updated in like 2 years.

Your primary competitor seems to be https://github.com/newrelic/wiki-sync-action. Most of the others appear abandoned.

Here's a non-exhaustive list of the other options:

- https://github.com/marketplace/actions/wiki-sync
- https://github.com/marketplace/actions/wiki-action
- https://github.com/marketplace/actions/update-wiki
- https://github.com/marketplace/actions/wiki-update
- https://github.com/marketplace/actions/github-wiki-sync-action
- https://github.com/marketplace/actions/publish-to-github-wiki
- https://github.com/marketplace/actions/wiki-page-creator-action
- https://github.com/marketplace/actions/github-wiki-action
- https://github.com/marketplace/actions/github-docs-to-wiki
- https://github.com/marketplace/actions/publish-readmes-to-github-wiki
- https://github.com/marketplace/actions/external-repo-wiki-sync-action
- https://github.com/marketplace/actions/bi-directional-wiki-sync-action
- https://github.com/marketplace/actions/update-wiki-with-php-project-documentation
- https://github.com/marketplace/actions/pencil_pusher

**Comment by spenserblack** [comment]
Wow, thanks for all this research!

The first thing that sticks out to me is that `wiki-sync-action` is a Docker action, which means that it can't be run in Windows actions (`runs-on: windows-latest`) AFAIK. Please correct me if I'm wrong about this 🙂 
I'll try to keep support for jobs that run on Ubuntu, MacOS, and Windows, which means I'll limit this to either being a composite action (as it is currently), or a Node.js action.

The next thing I notice is that it looks like `wiki-sync-action` performs a diff to know if it should commit changes or not. Currently, this action naively attempts to always commit changes when it's run. I wrote this with the assumption that the workflow would be set up to avoid runs without changes (e.g. `paths: [ '.github/wiki/*' ]`). I'm open to adding this check, but I don't have a need for it myself.

Finally, `wiki-sync-action` is bi-directional. It looks like, if the wiki is edited, those changes can  pulled down and cloned to the repo. I wrote this action for https://github.com/o2sh/onefetch/issues/925, and didn't consider a bi-directional sync. My single goal was to expose the wiki to PRs, so that people who aren't collaborators can contribute to the wiki and go through a review process. Bad things can happen when the wiki is directly editable by everyone :laughing: I don't really have any plans to make this bi-directional.

**Comment by spenserblack** [comment]
I'll accept a PR to add this comparison if you want to make one. I think we just need to compare with the most popular ones. The comparison could link to this issue for more context.

**Comment by jcbhmr** [comment]
Sounds good! 👍 I'll do just that.

**Comment by jcbhmr** [comment]
Thanks for answering my question. Closing this issue since it has been answered. Progress to adding the alternatives section to the readme can be found in #6.

**Comment by jcbhmr** [comment]
> I'll try to keep support for jobs that run on Ubuntu, MacOS, and Windows, which means I'll limit this to either being a composite action (as it is currently), or a Node.js action.

I just investigated this today, and I _think_ you can use Bash on Windows (with Git bash):

![image](https://user-images.githubusercontent.com/61068799/223888478-c7f915cc-2836-48ba-b151-6afe6b0840e7.png)

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

Just thought I'd put this here for posterity and future me.

**Comment by jcbhmr** [comment]
Turns out it's the same list for the composite action.yml file: 
![image](https://user-images.githubusercontent.com/61068799/223895502-c2a54127-b5ac-41b7-81b1-d1dfee0b3ad2.png)
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsshell
