### ISSUE TITLE
Consider reducing config clutter?

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#84]
Having dist in source control is _ok_ (if a little distasteful, but I digress) but there's **a lot** of clutter here! 🤮 I think we should reduce the clutter! 😁
![image](https://github.com/spenserblack/actions-wiki/assets/61068799/f41ab567-40d0-4127-8f6e-ba20b2e3a767)

Some ideas:
- Use Node.js' new `node:test` and `node --test` builtin test runner https://nodejs.org/api/test.html (removes jest config) or use https://vitest.dev/ which supports TS out of the box (zero-config)
- remove dist from source control so that you can `prettier --ignore-path .gitignore`
- move prettierrc to `prettier: {}` in package.json
- put contributors in a `<details>` dropdown at the bottom of the readme? (removes CREDITS.md) (https://allcontributors.org/docs/en/bot/installation#3-create-a-readmemd)
- remove .editorconfig and rely on running `prettier -w .` to even things out? Relying on CLI tools is the lowest common denominator; [even VS Code needs an extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)

Of those, I think these are the most feasible (easy)
- [ ] prettierrc ➡ package.json
- [ ] CREDITS.md ➡ README.md `<details>` 
- [ ] jest ➡ vitest/`node:test`

**Comment by spenserblack** [comment]
> Having dist in source control is _ok_

Borders on required for any Node.js action if you want to allow users to use it from `@main`, since AFAIK each action is checked out from the specified ref.

******

- Moving prettier config to package.json "unclutters" file tree by cluttering `package.json`, right? :wink:
- I'm going to need a better argument for switching testing tools than "we can remove a config file"
